services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: landale
      POSTGRES_USER: landale
      POSTGRES_PASSWORD: landale
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U landale -d landale']
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-development}
    restart: unless-stopped
    working_dir: /app/apps/server
    environment:
      DATABASE_URL: postgres://landale:landale@db:5432/landale
      NODE_ENV: ${NODE_ENV:-development}
    env_file:
      - .env
    ports:
      - '7175:7175'
      - '8080:8080'
      - '8081:8081'
    depends_on:
      db:
        condition: service_healthy
    command: ['bun', 'run', 'src/index.ts']
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 0.0.0.0 7175 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  overlays:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-development}
    restart: unless-stopped
    working_dir: /app/apps/overlays
    volumes:
      - emotes_cache:/app/apps/overlays/public/emotes
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - '8008:8008'
    depends_on:
      - server
    command: ['bunx', '--bun', 'vite']

volumes:
  postgres_data:
  emotes_cache:
