services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: landale
      POSTGRES_USER: landale
      POSTGRES_PASSWORD: landale
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U landale -d landale']
      interval: 10s
      timeout: 5s
      retries: 5
    command: ['postgres', '-c', 'log_min_messages=error']

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
      target: runtime
    restart: unless-stopped
    volumes:
      - server_data:/app/data
    environment:
      DATABASE_URL: postgres://landale:landale@db:5432/landale
      MIX_ENV: prod
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-insecure_default_key_for_development_only}
      PHX_HOST: ${PHX_HOST:-localhost}
      PORT: ${PORT:-8080}
    env_file:
      - .env
    ports:
      - '7175:7175'
      - '8080:8080'
      - '8081:8081'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', '/app/bin/server', 'rpc', ':ok']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "zelan:100.112.39.113"
      - "alys:100.106.79.5"
      - "demi:100.106.173.14"
      - "saya:100.122.53.119"

  # overlays:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: ${DOCKER_TARGET:-development}
  #   restart: unless-stopped
  #   working_dir: /app/apps/overlays
  #   volumes:
  #     - emotes_cache:/app/apps/overlays/public/emotes
  #   environment:
  #     NODE_ENV: ${NODE_ENV:-development}
  #   ports:
  #     - '8008:8008'
  #   depends_on:
  #     - server
  #   command: ['bunx', '--bun', 'vite']

  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: True
    ports:
      - '5341:80'     # Seq Web UI and Ingestion API (internal port 80, external 5341)
    volumes:
      - seq_data:/data
    healthcheck:
      test: ['CMD', '/bin/sh', '-c', 'wget -q -O /dev/null http://localhost/api/diagnostics/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  emotes_cache:
  server_data:
  seq_data:
