services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: landale
      POSTGRES_USER: landale
      POSTGRES_PASSWORD: landale
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U landale -d landale']
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-development}
    restart: unless-stopped
    working_dir: /app/apps/server
    volumes:
      # Only mount source directories, not the entire project
      - ./apps/server/src:/app/apps/server/src
      - ./packages:/app/packages
      # Exclude node_modules from being overwritten by host
      - /app/node_modules
      - /app/apps/server/node_modules
    environment:
      DATABASE_URL: postgres://landale:landale@db:5432/landale
      NODE_ENV: ${NODE_ENV:-development}
    env_file:
      - .env
    ports:
      - '7175:7175'
      - '8080:8080'
      - '8081:8081'
    depends_on:
      db:
        condition: service_healthy
    command: ['bun', 'run', 'src/index.ts']
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 0.0.0.0 7175 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  overlays:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-development}
    restart: unless-stopped
    working_dir: /app/apps/overlays
    volumes:
      # Only mount source directories
      - ./apps/overlays/src:/app/apps/overlays/src
      - ./apps/overlays/public:/app/apps/overlays/public
      - ./packages:/app/packages
      # Exclude node_modules
      - /app/node_modules
      - /app/apps/overlays/node_modules
      # Persistent emote cache
      - emotes_cache:/app/apps/overlays/public/emotes
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - '8008:8008'
    depends_on:
      - server
    command: ['bunx', '--bun', 'vite']

  audio-receiver:
    build:
      context: .
      dockerfile: apps/audio-receiver/Dockerfile
    restart: unless-stopped
    working_dir: /app/apps/audio-receiver
    volumes:
      - ./apps/audio-receiver/src:/app/apps/audio-receiver/src
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/audio-receiver/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      AUDIO_RECEIVER_PORT: 8889
    ports:
      - '8889:8889'
      - '8890:8890'
    depends_on:
      - server
    command: ['bun', 'run', 'dev']

volumes:
  postgres_data:
  emotes_cache:
