version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: landale
      POSTGRES_USER: landale
      POSTGRES_PASSWORD: landale
    ports:
      - '5433:5432'

  server:
    build: .
    working_dir: /workspace/packages/server
    volumes:
      - ./:/workspace
    environment:
      DATABASE_URL: postgres://landale:landale@db:5432/landale
    ports:
      - '7175:7175'
      - '8080:8080'
      - '8081:8081'

  overlays:
    build: .
    working_dir: /workspace/packages/overlays
    volumes:
      - ./:/workspace
    ports:
      - '8088:8088'
    depends_on:
      - server
      - db

volumes:
  postgres_data:
