/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as widgetOmnywidgetImport } from './routes/(widget)/omnywidget'
import { Route as fullIronmonImport } from './routes/(full)/ironmon'
import { Route as fullFoundationImport } from './routes/(full)/foundation'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const widgetOmnywidgetRoute = widgetOmnywidgetImport.update({
  path: '/omnywidget',
  getParentRoute: () => rootRoute,
} as any)

const fullIronmonRoute = fullIronmonImport.update({
  path: '/ironmon',
  getParentRoute: () => rootRoute,
} as any)

const fullFoundationRoute = fullFoundationImport.update({
  path: '/foundation',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(full)/foundation': {
      preLoaderRoute: typeof fullFoundationImport
      parentRoute: typeof rootRoute
    }
    '/(full)/ironmon': {
      preLoaderRoute: typeof fullIronmonImport
      parentRoute: typeof rootRoute
    }
    '/(widget)/omnywidget': {
      preLoaderRoute: typeof widgetOmnywidgetImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  fullFoundationRoute,
  fullIronmonRoute,
  widgetOmnywidgetRoute,
])

/* prettier-ignore-end */
