defmodule Server.Ironmon.Seed do
  @moduledoc """
  Ecto schema for IronMON challenge seeds/runs.
  """

  use Ecto.Schema
  import Ecto.Changeset

  # IMPORTANT: id is NOT autogenerated - it comes from IronMON plugin seed count
  @primary_key {:id, :integer, autogenerate: false}
  schema "seeds" do
    belongs_to :challenge, Server.Ironmon.Challenge
    has_many :results, Server.Ironmon.Result
  end

  def changeset(seed, attrs) do
    seed
    |> cast(attrs, [:id, :challenge_id])
    |> validate_required([:id, :challenge_id])
    |> foreign_key_constraint(:challenge_id)
  end
end
