/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceStatusRouteImport } from './routes/service-status'
import { Route as OauthRouteImport } from './routes/oauth'
import { Route as IndexRouteImport } from './routes/index'

const ServiceStatusRoute = ServiceStatusRouteImport.update({
  id: '/service-status',
  path: '/service-status',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRoute = OauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oauth': typeof OauthRoute
  '/service-status': typeof ServiceStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth': typeof OauthRoute
  '/service-status': typeof ServiceStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oauth': typeof OauthRoute
  '/service-status': typeof ServiceStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oauth' | '/service-status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oauth' | '/service-status'
  id: '__root__' | '/' | '/oauth' | '/service-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OauthRoute: typeof OauthRoute
  ServiceStatusRoute: typeof ServiceStatusRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/service-status': {
      id: '/service-status'
      path: '/service-status'
      fullPath: '/service-status'
      preLoaderRoute: typeof ServiceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OauthRoute: OauthRoute,
  ServiceStatusRoute: ServiceStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
