/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakeoverRouteImport } from './routes/takeover'
import { Route as RainwaveRouteImport } from './routes/rainwave'
import { Route as OmnibarRouteImport } from './routes/omnibar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsIronmonFullRouteImport } from './routes/shows/ironmon/full'

const TakeoverRoute = TakeoverRouteImport.update({
  id: '/takeover',
  path: '/takeover',
  getParentRoute: () => rootRouteImport,
} as any)
const RainwaveRoute = RainwaveRouteImport.update({
  id: '/rainwave',
  path: '/rainwave',
  getParentRoute: () => rootRouteImport,
} as any)
const OmnibarRoute = OmnibarRouteImport.update({
  id: '/omnibar',
  path: '/omnibar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIronmonFullRoute = ShowsIronmonFullRouteImport.update({
  id: '/shows/ironmon/full',
  path: '/shows/ironmon/full',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/omnibar': typeof OmnibarRoute
  '/rainwave': typeof RainwaveRoute
  '/takeover': typeof TakeoverRoute
  '/shows/ironmon/full': typeof ShowsIronmonFullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/omnibar': typeof OmnibarRoute
  '/rainwave': typeof RainwaveRoute
  '/takeover': typeof TakeoverRoute
  '/shows/ironmon/full': typeof ShowsIronmonFullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/omnibar': typeof OmnibarRoute
  '/rainwave': typeof RainwaveRoute
  '/takeover': typeof TakeoverRoute
  '/shows/ironmon/full': typeof ShowsIronmonFullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/omnibar'
    | '/rainwave'
    | '/takeover'
    | '/shows/ironmon/full'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/omnibar' | '/rainwave' | '/takeover' | '/shows/ironmon/full'
  id:
    | '__root__'
    | '/'
    | '/omnibar'
    | '/rainwave'
    | '/takeover'
    | '/shows/ironmon/full'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OmnibarRoute: typeof OmnibarRoute
  RainwaveRoute: typeof RainwaveRoute
  TakeoverRoute: typeof TakeoverRoute
  ShowsIronmonFullRoute: typeof ShowsIronmonFullRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/takeover': {
      id: '/takeover'
      path: '/takeover'
      fullPath: '/takeover'
      preLoaderRoute: typeof TakeoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rainwave': {
      id: '/rainwave'
      path: '/rainwave'
      fullPath: '/rainwave'
      preLoaderRoute: typeof RainwaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omnibar': {
      id: '/omnibar'
      path: '/omnibar'
      fullPath: '/omnibar'
      preLoaderRoute: typeof OmnibarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/ironmon/full': {
      id: '/shows/ironmon/full'
      path: '/shows/ironmon/full'
      fullPath: '/shows/ironmon/full'
      preLoaderRoute: typeof ShowsIronmonFullRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OmnibarRoute: OmnibarRoute,
  RainwaveRoute: RainwaveRoute,
  TakeoverRoute: TakeoverRoute,
  ShowsIronmonFullRoute: ShowsIronmonFullRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
