name: Python CI

on:
  push:
    branches: [ main, feature/* ]
    paths: 
      - 'apps/phononmaser/**'
      - 'apps/seed/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/phononmaser/**'
      - 'apps/seed/**'

jobs:
  test:
    name: Test and Lint Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [phononmaser, seed]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.app == 'seed' && '3.13' || '3.11' }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.app }}-${{ hashFiles('apps/${{ matrix.app }}/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.app }}-

      - name: Install dependencies
        working-directory: apps/${{ matrix.app }}
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.app }}" == "seed" ]; then
            pip install -e . --config-settings editable-verbose=true
            pip install pytest pytest-asyncio ruff
          else
            pip install -e .[dev]
          fi

      - name: Run Ruff linting
        working-directory: apps/${{ matrix.app }}
        run: ruff check --diff

      - name: Run Ruff formatting check
        working-directory: apps/${{ matrix.app }}
        run: ruff format --diff

      - name: Run tests
        working-directory: apps/${{ matrix.app }}
        run: pytest