name: TypeScript CI

on:
  push:
    branches: [ main, feature/* ]
    paths: 
      - 'apps/overlays/**'
      - 'apps/dashboard/**'
      - 'packages/**'
      - 'turbo.json'
      - 'package.json'
      - 'bun.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/overlays/**'
      - 'apps/dashboard/**' 
      - 'packages/**'
      - 'turbo.json'
      - 'package.json'
      - 'bun.lock'

jobs:
  test:
    name: Test and Lint TypeScript
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run type checking
        run: turbo run typecheck --filter="!@landale/phononmaser" --filter="!@landale/seed"

      - name: Run linting
        run: turbo run lint --filter="!@landale/phononmaser" --filter="!@landale/seed"

      - name: Run tests
        run: turbo run test --filter="!@landale/phononmaser" --filter="!@landale/seed"