name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env << EOF
          # Twitch
          TWITCH_CLIENT_ID=${{ vars.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET=${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_EVENTSUB_SECRET=${{ secrets.TWITCH_EVENTSUB_SECRET }}
          TWITCH_USER_ID=${{ vars.TWITCH_USER_ID }}

          # Rainwave
          RAINWAVE_USER_ID=${{ vars.RAINWAVE_USER_ID }}
          RAINWAVE_API_KEY=${{ secrets.RAINWAVE_API_KEY }}

          # Control API Security
          CONTROL_API_KEY=${{ secrets.CONTROL_API_KEY }}
          EOF

      - name: Deploy with OrbStack
        run: |
          cd ${{ github.workspace }}
          docker compose down
          docker compose up -d --build
          docker image prune -f
