name: Deploy to OrbStack
on:
  push:
    branches: [main]
    paths:
      - 'apps/server/**'
      - 'apps/overlays/**'
      - 'packages/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env << EOF
          # Twitch API Configuration
          TWITCH_CLIENT_ID=${{ vars.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET=${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_EVENTSUB_SECRET=${{ secrets.TWITCH_EVENTSUB_SECRET }}
          TWITCH_USER_ID=${{ vars.TWITCH_USER_ID }}

          # Rainwave
          RAINWAVE_USER_ID=${{ vars.RAINWAVE_USER_ID }}
          RAINWAVE_API_KEY=${{ secrets.RAINWAVE_API_KEY }}

          # Database
          DATABASE_URL=${{ secrets.DATABASE_URL }}

          # Phoenix Configuration
          SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
          PHX_HOST=${{ vars.PHX_HOST }}
          PORT=${{ vars.PORT }}

          # Cloak Encryption Key
          CLOAK_SECRET_KEY=${{ secrets.CLOAK_SECRET_KEY }}
          EOF

      - name: Deploy with OrbStack
        run: |
          cd ${{ github.workspace }}
          docker compose down
          docker compose up -d --build
          docker image prune -f
